# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dkm-GVAG8ryjwq1wpozNrYjnXZBEggR8
"""

!pip -q install --upgrade transformers accelerate sentencepiece gradio --progress-bar off
print("✅ Libraries installed.")

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v0.6"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=220)

print("✅ Model loaded:", model_id)

import gradio as gr, textwrap, datetime, pathlib, re

TONE_STYLES = {
    "formal": "Professional and respectful tone suitable for business communication.",
    "friendly": "Warm and approachable, conversational tone.",
    "polite_assertive": "Polite but clearly states expectations and next steps.",
    "short_direct": "Concise and straight to the point.",
    "managerial": "Confident, structured tone addressing a team or stakeholder.",
    "complaint": "Firm yet courteous complaint requesting resolution.",
    "apology": "Sincere apology acknowledging responsibility and empathy."
}
ALL_TONES = list(TONE_STYLES.keys())
EXPORT_DIR = pathlib.Path("/content/exports"); EXPORT_DIR.mkdir(parents=True, exist_ok=True)
_timestamp = lambda: datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

def build_prompt(email_text, tone_instruction):
    return textwrap.dedent(f"""
    Rewrite the following email in this tone: {tone_instruction}

    Rules:
    - Do not add new facts, names, or numbers
    - Keep original meaning and intent
    - Use natural email structure (greeting, body, closing)
    - Finish completely
    Email:
    {email_text}
    """).strip()

def clean_trailing_sentence(text):
    parts = re.split(r'(?<=[.!?])\s+', text)
    if len(parts) > 1 and len(parts[-1]) < 15: parts = parts[:-1]
    return " ".join(parts).strip()

def generate_reply(prompt, temperature=0.5):
    try:
        messages = [
            {"role": "system", "content": (
                "You rewrite emails professionally without inventing facts. "
                "Keep them concise (5–8 sentences) and end properly.")},
            {"role": "user", "content": prompt}
        ]
        chat_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        out = pipe(chat_text, temperature=float(temperature), repetition_penalty=1.15, top_p=0.9)[0]["generated_text"]
        if "<|assistant|>" in out: out = out.split("<|assistant|>")[-1]
        return clean_trailing_sentence(out.strip())
    except Exception as e:
        return f"⚠️ Error: {e}"

def save_file(name, content):
    path = EXPORT_DIR / name; path.write_text(content, encoding="utf-8"); return str(path)

def rewrite_single(email_text, tone_key, temperature):
    if not email_text.strip(): return "⚠️ Paste an email first.", None
    prompt = build_prompt(email_text, TONE_STYLES[tone_key])
    output = generate_reply(prompt, temperature)
    f = f"email_{tone_key}_{_timestamp()}.txt"
    return output, save_file(f, output)

def rewrite_all(email_text, temperature):
    if not email_text.strip(): return "⚠️ Paste an email first.", None
    md = ["# Tone Comparison\n"]
    for tone in ALL_TONES:
        out = generate_reply(build_prompt(email_text, TONE_STYLES[tone]), temperature)
        md.append(f"## {tone.replace('_',' ').title()}\n```\n{out}\n```\n")
    text = "\n".join(md)
    f = f"email_all_tones_{_timestamp()}.md"
    return text, save_file(f, text)

INTRO = """
# ✉️ Email Tone Transformer — TinyLlama v0.6
✅ No login or token required
✅ 7 tone styles + adjustable temperature
"""

def ui_single(email, tone, temp): return rewrite_single(email, tone, temp)
def ui_all(email, temp): return rewrite_all(email, temp)

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown(INTRO)
    email_box = gr.Textbox(lines=12, label="Paste your email here")

    with gr.Accordion("Settings", open=True):
        tone_drop = gr.Dropdown(choices=ALL_TONES, value="formal", label="Tone")
        temp = gr.Slider(0.0, 1.2, 0.5, 0.1, label="Temperature")

    btn_one = gr.Button("✨ Rewrite Selected Tone")
    btn_all = gr.Button("🧪 Compare All Tones")

    single_out = gr.Textbox(lines=12, label="Rewritten Email", show_copy_button=True)
    single_file = gr.File(label="Download Result")
    multi_out = gr.Markdown(label="All Tones Comparison")
    multi_file = gr.File(label="Download All Tones (.md)")

    btn_one.click(ui_single, [email_box, tone_drop, temp], [single_out, single_file])
    btn_all.click(ui_all, [email_box, temp], [multi_out, multi_file])

demo.launch()